# Generated by Django 4.2.2 on 2023-06-30 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatIDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatid', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='messages',
            name='roomchatIDreverse',
        ),
        migrations.AlterField(
            model_name='messages',
            name='roomchatID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.chatids'),
        ),
    ]
