# Generated by Django 4.2.2 on 2023-06-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatids_remove_messages_roomchatidreverse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatids',
            name='chatid',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
