# Generated by Django 4.2.2 on 2023-07-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatids_chatid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='pic',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
