# Generated by Django 4.2.2 on 2023-07-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_messages_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='messagesPictures/'),
        ),
    ]
