# Generated by Django 4.2.2 on 2023-07-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_messages_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='is_pic',
            field=models.BooleanField(default=False),
        ),
    ]
