# Generated by Django 4.2.2 on 2023-06-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_default_profile_pic',
            field=models.BooleanField(default=False),
        ),
    ]
