# Generated by Django 4.2.2 on 2023-06-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_is_default_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
    ]
