# Generated by Django 4.2.2 on 2023-06-30 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userprofile_calls_no_userprofile_whastapp_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
